import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'
import { GoogleAnalytics } from '@next/third-parties/google'
import './globals.css'

const bricGrotesque = Bricolage_Grotesque({
  subsets: ['latin'],
  variable: '--font-bricolage',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Takoyaki Game 🐙',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${bricGrotesque.className} antialiased`}>
        {children}
      </body>
      <GoogleAnalytics gaId="G-0SB60V67C6" />
    </html>
  )
}
